// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetPet.App.Persistencia;

namespace VetPet.App.Persistencia.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211006220530_InicialMySql")]
    partial class InicialMySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("VetPet.App.Dominio.Cita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("fecha")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("hora")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("mascotaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mascotaid");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("VetPet.App.Dominio.HistoriaClinica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("anotaciones")
                        .HasColumnType("longtext");

                    b.Property<int?>("citaid")
                        .HasColumnType("int");

                    b.Property<int?>("mascotaid")
                        .HasColumnType("int");

                    b.Property<string>("medicamento")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("citaid");

                    b.HasIndex("mascotaid");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Mascota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext");

                    b.Property<int?>("propietarioid")
                        .HasColumnType("int");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("propietarioid");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("apellido")
                        .HasColumnType("longtext");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("cedula")
                        .IsUnique();

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Propietario", b =>
                {
                    b.HasBaseType("VetPet.App.Dominio.Persona");

                    b.Property<string>("ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Propietario");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Veterinario", b =>
                {
                    b.HasBaseType("VetPet.App.Dominio.Persona");

                    b.Property<DateTime>("horario_entrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("horario_salida")
                        .HasColumnType("datetime(6)");

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Admin", b =>
                {
                    b.HasBaseType("VetPet.App.Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Cita", b =>
                {
                    b.HasOne("VetPet.App.Dominio.Mascota", "mascota")
                        .WithMany()
                        .HasForeignKey("mascotaid");

                    b.Navigation("mascota");
                });

            modelBuilder.Entity("VetPet.App.Dominio.HistoriaClinica", b =>
                {
                    b.HasOne("VetPet.App.Dominio.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("citaid");

                    b.HasOne("VetPet.App.Dominio.Mascota", "mascota")
                        .WithMany()
                        .HasForeignKey("mascotaid");

                    b.Navigation("cita");

                    b.Navigation("mascota");
                });

            modelBuilder.Entity("VetPet.App.Dominio.Mascota", b =>
                {
                    b.HasOne("VetPet.App.Dominio.Propietario", "propietario")
                        .WithMany()
                        .HasForeignKey("propietarioid");

                    b.Navigation("propietario");
                });
#pragma warning restore 612, 618
        }
    }
}
